### ISSUE TITLE
Broken Pipe Exception during write to stream

### ISSUE THREAD

**Issue by tamnm** [nats-io/nats.net.v1#193]
I got this exception for around each 30mins

System.Net.Sockets.SocketException (0x80004005): Broken pipe
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   
System.Net.Sockets.SocketException (0x80004005): Connection reset by peer
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)

do you have any idea?

Nats and my service are on same machine. Both running well.

**Comment by tamnm** [comment]
this from my log

2017/11/14 03:24:05.691: System.Net.Sockets.SocketException (0x80004005): Broken pipe
2017/11/14 03:29:09.362: System.Net.Sockets.SocketException (0x80004005): Broken pipe
2017/11/14 03:40:16.726: System.Net.Sockets.SocketException (0x80004005): Broken pipe
2017/11/14 04:05:26.198: System.Net.Sockets.SocketException (0x80004005): Broken pipe
2017/11/14 04:11:14.794: System.Net.Sockets.SocketException (0x80004005): Broken pipe
2017/11/14 04:31:29.462: System.Net.Sockets.SocketException (0x80004005): Broken pipe
2017/11/14 05:11:29.066: System.Net.Sockets.SocketException (0x80004005): Broken pipe
2017/11/14 05:19:47.110: System.Net.Sockets.SocketException (0x80004005): Broken pipe
2017/11/14 05:29:12.498: System.Net.Sockets.SocketException (0x80004005): Broken pipe
2017/11/14 05:34:23.730: System.Net.Sockets.SocketException (0x80004005): Broken pipe
2017/11/14 05:45:49.573: System.Net.Sockets.SocketException (0x80004005): Broken pipe
2017/11/14 06:12:05.710: System.Net.Sockets.SocketException (0x80004005): Broken pipe
2017/11/14 06:12:05.710: System.Net.Sockets.SocketException (0x80004005): Broken pipe
2017/11/14 06:12:52.851: System.Net.Sockets.SocketException (0x80004005): Broken pipe

**Comment by ColinSullivan1** [comment]
@tamnm , this looks like something odd is going on with your network stack; perhaps your network interface/driver is being periodically restarted.  If you use loopback (127.0.0.1), do you still see the issue?

**Comment by ColinSullivan1** [comment]
Closing due to inactivity.
