### ISSUE TITLE
Unstable SSL

### ISSUE THREAD

**Issue by dioptre** [nats-io/nats.net.v1#196]
Hi I *sometimes* get this:
```
TLS Authentication error ---> System.IO.IOException: The handshake failed due to an unexpected packet format.
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.BeginAuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.Security.SslStream.<>c__DisplayClass32_0.<AuthenticateAsClientAsync>b__0(AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
   at System.Net.Security.SslStream.AuthenticateAsClientAsync(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
   at NATS.Client.Connection.TCPConnection.makeTLS(Options options)
   --- End of inner exception stack trace ---
   at NATS.Client.Connection.connect()
```

I'm running 50 instances of a test service and am using NATS to connect when this happens on boot. Only 10% of the clients connect. I've never had an issue with other language's drivers before. 

Thanks for any help
Andy

**Comment by dioptre** [comment]
BTW I removed the following lines:
```
//X509Certificate2 cert = new X509Certificate2("client.pfx", "");
//opts.AddCertificate(cert);   
```
And it worked. Scary that this could happen though.

**Comment by ColinSullivan1** [comment]
@dioptre , thank you for raising this issue.

It seems the client is receiving invalid data in the TLS handshake.  I have a few questions:

* Which version of the NATS server (gnatsd) are you using?
* Are a high number of clients attempting to connect to the NATS server at the same time?
* Would you have NATS server logs available?  (logs with `-D` (debug) or `-DV` (debug+trace) would be helpful. 
* What versions of the C# client and .NET are being used?

This reminds me of https://github.com/nats-io/gnatsd/issues/432...

Thanks,
Colin

**Comment by ColinSullivan1** [comment]
I'm closing this issue - please reopen if you are still encountering errors.  We can see this when a large number of clients attempt to connect to the NATS server simultaneously using TLS, or when the server is on a machine without enough CPU resources to handle the incoming TLS requests.  The server times out, and sends an error back to the client while the client is still negotiating TLS.  The client interprets this as invalid data.  By increasing the TLS and handshake timeout in the NATS server, you can mitigate this.
