### ISSUE TITLE
Unable to fail over in clustered setup

### ISSUE THREAD

**Issue by CrossBound** [nats-io/nats.net.v1#315]
I brought this up in Slack but thought it might be better to just create an issue here so we can better track the issue. 

I have been testing a clustered setup and when one of my nodes goes offline my c# clients fail to connect to the other cluster nodes. Once the down node comes back online the client still will not reconnect and will have to be killed and restarted to get it to connect again. I've tried this with the latest pre-release and that made no difference. I've tried it on .net 4.7.2 as well as .net core 3 and both have the same result.

My last test did not include any TLS or auth and it still didn't work. I can connect to both servers directly. I'm clustering like this on the seed server:

`nats-server -DV -p 4222 -m 8222 --cluster nats://0.0.0.0:6222`

And on the secondary (172.16.1.118 is the seed server):  

`nats-server -p 4222 -m 8222 --cluster nats://0.0.0.0:6222 --routes nats://172.16.1.118:6222 -DV`

I've seen different exception messages depending on where the process was at the time the server went offline, but here is an example: 

```
NATS.Client.NATSException: Flush error. ---> System.IO.IOException: Unable to write data to the transport connection: An established connection was aborted by the software in your host machine. ---> System.Net.Sockets.SocketException: An established connection was aborted by the software in your host machine
  at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
  --- End of inner exception stack trace ---
  at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
  at System.Net.Security.SslStreamInternal.WriteSingleChunk[TWriteAdapter](TWriteAdapter writeAdapter, ReadOnlyMemory`1 buffer)
  at System.Net.Security.SslStreamInternal.WriteAsyncInternal[TWriteAdapter](TWriteAdapter writeAdapter, ReadOnlyMemory`1 buffer)
  at System.Net.Security.SslStreamInternal.Write(Byte[] buffer, Int32 offset, Int32 count)
  at System.Net.Security.SslStream.Write(Byte[] buffer, Int32 offset, Int32 count)
  at System.IO.BufferedStream.Flush()
  at NATS.Client.Connection.Flush(Int32 timeout)
  --- End of inner exception stack trace ---
  at NATS.Client.Connection.Flush(Int32 timeout)
  at LegacyBank.LEAF.Messaging.NATS.NatsPublisher.<>c__DisplayClass7_0`2.<RequestReplyAsync>b__0()
  at System.Threading.Tasks.Task`1.InnerInvoke()
  at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
  at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
  at LegacyBank.LEAF.Authentication.Customer.Models.NatsPinValidator.ValidatePinAsync(UInt64 CAN, UInt64 PIN, CancellationToken CancellationToken) in D:\Projects\LEAF\Services\CustomerAuthentication\API\Models\NatsPinValidator.cs:line 42
  at LegacyBank.LEAF.Authentication.Customer.Models.VruGrantValidator.ValidateAsync(ExtensionGrantValidationContext Context) in D:\Projects\LEAF\Services\CustomerAuthentication\API\Models\VruGrantValidator.cs:line 50
```

I will post a working application that exhibits the problem.

**Comment by CrossBound** [comment]
My nats-servers are both running on a bare-bones Debian 10 servers. Other than a static IP address they don't have any special configuration.

**Comment by CrossBound** [comment]
Here is a very basic repro: https://github.com/CrossBound/NATS-Performance-Benchmarking

And here is what I get: 
![image](https://user-images.githubusercontent.com/11417093/68080623-4d637f00-fdcd-11e9-8170-f7b659d589ab.png)

**Comment by CrossBound** [comment]
Here's a better screenshot with exception types:

![image](https://user-images.githubusercontent.com/11417093/68080721-0ffff100-fdcf-11e9-850c-1a2fbcf97126.png)

**Comment by CrossBound** [comment]
```
Starting publisher
Publishing
[00:22:19] Published in 17.310 ms
[00:22:20] Published in 3.032 ms
[00:22:21] Published in 2.555 ms
[00:22:22] Published in 2.635 ms
[00:22:23] Published in 2.321 ms
[00:22:26] Connection Error: (n/a) n/a
[00:22:26] Local Error: (NATSTimeoutException) Timeout occurred.
[00:22:27] Connection Error: (n/a) n/a
[00:22:27] Local Error: (NATSException) Flush error.
    Inner Error: (IOException) Unable to write data to the transport connection: An established connection was aborted by the software in your host machine..
       Inner Error: (SocketException) An established connection was aborted by the software in your host machine.
[00:22:28] Connection Error: (n/a) n/a
[00:22:28] Local Error: (NATSException) Flush error.
    Inner Error: (IOException) Unable to write data to the transport connection: An established connection was aborted by the software in your host machine..
       Inner Error: (SocketException) An established connection was aborted by the software in your host machine.
[00:22:29] Connection Error: (n/a) n/a
[00:22:29] Local Error: (NATSException) Flush error.
    Inner Error: (IOException) Unable to write data to the transport connection: An established connection was aborted by the software in your host machine..
       Inner Error: (SocketException) An established connection was aborted by the software in your host machine.
[00:22:30] Connection Error: (n/a) n/a
[00:22:30] Local Error: (NATSException) Flush error.
    Inner Error: (IOException) Unable to write data to the transport connection: An established connection was aborted by the software in your host machine..
       Inner Error: (SocketException) An established connection was aborted by the software in your host machine.
Press enter to exit:
```

**Comment by ColinSullivan1** [comment]
@CrossBound , thank you for providing an example application demonstrating the problem.  We'll take a look.  As we discussed on slack, we haven't seen this in our testing, but hopefully we can narrow in the issue you are seeing here.

**Comment by ColinSullivan1** [comment]
Another thing that would really help us out would be complete output of the servers with the `-DV` flag set (debug + trace).

**Comment by CrossBound** [comment]
Logs Attached:

At 11:33 I started both servers in clustered configuration
I connected my consumer to the secondary server (172.16.1.119)
I connected my publisher to the seed server (172.16.1.118)
They were passing messages in request/reply just fine across the clustered servers.

At 11:35 I restarted the seed server, but my publisher never re-connected.

I finally ended my publisher process at 11:37 and exited the servers.

[nats-seed-log.txt](https://github.com/nats-io/nats.net/files/3805326/nats-seed-log.txt)
[nats-secondary-log.txt](https://github.com/nats-io/nats.net/files/3805327/nats-secondary-log.txt)

**Comment by ColinSullivan1** [comment]
Thanks you @CrossBound.  What does [IConnection.DiscoveredServers](http://nats-io.github.io/nats.net/interface_n_a_t_s_1_1_client_1_1_i_connection.html#af67e98d92452ead23d62cd51ebc0191a) return after you are connected and the NATS servers are routed?  I'm wondering if your secondary server is advertising a different hostname/ip than what you need to connect to it.

**Comment by CrossBound** [comment]
nats://172.16.1.119:4222

**Comment by CrossBound** [comment]
It works fine to connect to 172.16.1.119:4222 directly. When I do that the DiscoveredServers correctly reports nats://172.16.1.118:4222

**Comment by CrossBound** [comment]
interesting observation: I added disconnect and close event handlers... they never fired when I killed the server process. They didn't fire until I ended the program. 

Should they fire when a problem on the connection occurs?

**Comment by CrossBound** [comment]
The AsyncError, ServerDiscovered, and Reconnected events never fired at all.

**Comment by ColinSullivan1** [comment]
Yes, they should fire...   On linux, .NET can take a long time to detect closed sockets.  What happens when you set your [Options.PingInterval](http://nats-io.github.io/nats.net/class_n_a_t_s_1_1_client_1_1_options.html#a5b593b856ab2b9df03637efdffff135c) to something low, like 2000 (2 seconds)?

**Comment by CrossBound** [comment]
I set the ping interval to 1000 milliseconds and it reconnected shortly after.

```
Starting publisher
Publishing
[14:25:36] Published in 15.179 ms (nats://172.16.1.119:4222)
[14:25:37] Published in 2.570 ms (nats://172.16.1.119:4222)
[14:25:38] Published in 2.562 ms (nats://172.16.1.119:4222)
[14:25:39] Published in 2.381 ms (nats://172.16.1.119:4222)
[14:25:40] Published in 2.788 ms (nats://172.16.1.119:4222)
[14:25:41] Published in 2.934 ms (nats://172.16.1.119:4222)
[14:25:42] Published in 2.837 ms (nats://172.16.1.119:4222)
[14:25:43] Published in 2.499 ms (nats://172.16.1.119:4222)
[14:25:44] Published in 2.828 ms (nats://172.16.1.119:4222)
[14:25:45] Published in 2.490 ms (nats://172.16.1.119:4222)
[14:25:46] Published in 2.474 ms (nats://172.16.1.119:4222)
[14:25:47] Published in 2.340 ms (nats://172.16.1.119:4222)
[14:25:48] Published in 2.852 ms (nats://172.16.1.119:4222)
[14:25:49] Published in 2.297 ms (nats://172.16.1.119:4222)
[14:25:50] Published in 2.632 ms (nats://172.16.1.119:4222)
[14:25:51] Published in 2.263 ms (nats://172.16.1.119:4222)
[14:25:52] Published in 2.325 ms (nats://172.16.1.119:4222)
[14:25:53] Connection Error: (n/a) n/a
[14:25:53] Local Error: (NATSException) Flush error.
    Inner Error: (IOException) Unable to write data to the transport connection: An established connection was aborted by the software in your host machine..
       Inner Error: (SocketException) An established connection was aborted by the software in your host machine.
[14:25:54] Connection Error: (n/a) n/a
[14:25:54] Local Error: (NATSException) Flush error.
    Inner Error: (IOException) Unable to write data to the transport connection: An established connection was aborted by the software in your host machine..
       Inner Error: (SocketException) An established connection was aborted by the software in your host machine.
DisconnectedEventHandler fired [ ]
ReconnectedEventHandler fired
[14:25:55] Published in 13.710 ms (nats://172.16.1.119:4222)
[14:25:56] Published in 2.070 ms (nats://172.16.1.119:4222)
[14:25:57] Published in 2.108 ms (nats://172.16.1.119:4222)
[14:25:58] Published in 2.135 ms (nats://172.16.1.119:4222)
[14:25:59] Published in 2.290 ms (nats://172.16.1.119:4222)
[14:26:00] Published in 2.423 ms (nats://172.16.1.119:4222)
[14:26:01] Published in 2.303 ms (nats://172.16.1.119:4222)
[14:26:02] Published in 2.034 ms (nats://172.16.1.119:4222)
[14:26:03] Published in 2.109 ms (nats://172.16.1.119:4222)
[14:26:04] Published in 2.190 ms (nats://172.16.1.119:4222)
[14:26:05] Published in 2.265 ms (nats://172.16.1.119:4222)
[14:26:06] Published in 1.875 ms (nats://172.16.1.119:4222)
[14:26:07] Published in 2.734 ms (nats://172.16.1.119:4222)
[14:26:08] Published in 2.113 ms (nats://172.16.1.119:4222)
[14:26:09] Published in 2.282 ms (nats://172.16.1.119:4222)
[14:26:10] Published in 3.170 ms (nats://172.16.1.119:4222)
DisconnectedEventHandler fired [ ]
ClosedEventHandler fired [ ]
Press enter to exit:
```

**Comment by ColinSullivan1** [comment]
So that was it!  I'm sorry we didn't reach this conclusion earlier, thanks for your patience on this issue @CrossBound.  I'd go with the maximum you can tolerate depending on the # of clients you have.  e.g. if you have 1000 clients, 1 per sec will add 2000 protocol msgs/sec (a ping to the server and a pong back).  Not a big deal for NATS, but just be aware of the chatter.

**Comment by CrossBound** [comment]
I'm running Flush() after each message. That's already sending a PING to the server... is there not a way to piggy back off that to detect a connection failure?

**Comment by CrossBound** [comment]
Seems kinda odd that my flush could be failing but the connection would wait until it's own internal ping timer to reach the conclusion the connection is not working.

**Comment by ColinSullivan1** [comment]
I'd require some work.  You can check for an exception there, and then reconnect randomly to a new server you've found from discovered servers.  I'll look into that, where a flush failure could trigger a reconnect.  Today we key off of the underlying socket state when reading from the socket - if the .NET framework doesn't report a broke connection quickly we won't detect it outside of the ping timer.

**Comment by CrossBound** [comment]
As a side note: I noticed in the Closed and Disconnected event handlers the ConnectionID and ConnectionURL come back String.Empty and null respectively. Is that expected behavior?

**Comment by CrossBound** [comment]
Is there a way to manually trigger a Connection.ReConnect() or will I have to manually Close() and new up a new connection?

**Comment by ColinSullivan1** [comment]
You'll need to manually close and setup another connection.  I'd suggest the ping interval solution unless you cannot tolerate any downtime.

**Comment by CrossBound** [comment]
Yeah, I'm worried about manually re-connecting because that means I have to deal with all the subscriptions, etc. that are tied to the connection. 

I'm trying to use NATS instead of HTTPS as a transport between micro services so we will not have a very high tolerance level for downtime.

**Comment by ColinSullivan1** [comment]
How many clients?  If under 100 or so, then you could go down as low as a 100ms PingInterval.   I do think a reconnect API to trigger a reconnect would be useful.

Also, you can configure the OS to respond quickly through sysctl.  Check out:

* https://knowledgebase.progress.com/articles/Article/000044970
* https://www.tldp.org/HOWTO/html_single/TCP-Keepalive-HOWTO/
* https://blog.voina.org/tcp-keepalive-what-is-it-why-do-you-need-it-how-to-configure-it-on-linux/

This is the same behaviour you'd normally see when a connection isn't cleanly closed (e.g. cutting/pulling a network cable or stopping the NATS server docker image).

**Comment by ColinSullivan1** [comment]
This could be related to #326, we'll investigate further.

**Comment by ColinSullivan1** [comment]
@CrossBound , would you mind trying `set NATS_DOCKERIZED=1` and running your reconnect tests?  It'd confirm that your issue is the same as #326.

**Comment by ColinSullivan1** [comment]
#329, which is included in the new release should resolve this, please re-open this issue if you continue to have problems.

**Comment by CrossBound** [comment]
FYI, version 0.10.0 fixes my issue and now my connections are failing over immediately as expected.

Thanks

**Comment by ColinSullivan1** [comment]
@CrossBound , glad this resolved your issue.  Apologies for the false starts in solving this one and we really appreciate your time helping us track down the problem.
