### ISSUE TITLE
Unexpected exception when connecting

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/nats.net.v1#378]
When `opts.SetUserCredentials` is set and the client connects to a server without authorization enabled, an unexpected exception is thrown. 

```Exception: String reference not set to an instance of a String. (Parameter 's')
System.ArgumentNullException: String reference not set to an instance of a String. (Parameter 's')
   at NATS.Client.Connection.connect()
   at NATS.Client.ConnectionFactory.CreateConnection(Options opts)
   at TestNGS.Program.Run(String[] argss) in /Users/colinsullivan/Projects/TestNGS/Program.cs:line 56
   at TestNGS.Program.Main(String[] args) in /Users/colinsullivan/Projects/TestNGS/Program.cs:line 67```

**Comment by ColinSullivan1** [comment]
Going back to this, I was unable to reproduce it.
