### ISSUE TITLE
Pull-based consumer no longer receiving messages

### ISSUE THREAD

**Issue by Exagram** [nats-io/nats.net.v1#621]
I am keeping a NATS connection for a couple of hours (~1 day). Suddenly I'm getting issues connecting to it. Restarting both NATS server and my .NET application doesn't fix it. Thoughts?

In Powershell I ran the server:
```
PS > nats-server -js
[8736] 2022/06/23 09:08:40.502937 [INF] Starting nats-server
[8736] 2022/06/23 09:08:40.505032 [INF]   Version:  2.7.2
[8736] 2022/06/23 09:08:40.505032 [INF]   Git:      [135475b]
[8736] 2022/06/23 09:08:40.505032 [INF]   Name:     REDACTED
[8736] 2022/06/23 09:08:40.505032 [INF]   Node:     REDACTED
[8736] 2022/06/23 09:08:40.505032 [INF]   ID:       REDACTED
[8736] 2022/06/23 09:08:40.506075 [INF] Starting JetStream
[8736] 2022/06/23 09:08:40.507114 [INF]     _ ___ _____ ___ _____ ___ ___   _   __  __
[8736] 2022/06/23 09:08:40.507114 [INF]  _ | | __|_   _/ __|_   _| _ \ __| /_\ |  \/  |
[8736] 2022/06/23 09:08:40.507641 [INF] | || | _|  | | \__ \ | | |   / _| / _ \| |\/| |
[8736] 2022/06/23 09:08:40.507641 [INF]  \__/|___| |_| |___/ |_| |_|_\___/_/ \_\_|  |_|
[8736] 2022/06/23 09:08:40.507641 [INF]
[8736] 2022/06/23 09:08:40.507641 [INF]          https://docs.nats.io/jetstream
[8736] 2022/06/23 09:08:40.507641 [INF]
[8736] 2022/06/23 09:08:40.507641 [INF] ---------------- JETSTREAM ----------------
[8736] 2022/06/23 09:08:40.507641 [INF]   Max Memory:      23.81 GB
[8736] 2022/06/23 09:08:40.507641 [INF]   Max Storage:     1.00 TB
[8736] 2022/06/23 09:08:40.507641 [INF]   Store Directory: "C:\Users\REDACTED\AppData\Local\Temp\nats\jetstream"
[8736] 2022/06/23 09:08:40.507641 [INF] -------------------------------------------
[8736] 2022/06/23 09:08:40.512357 [INF]   Restored 608 messages for stream "MAIN"
[8736] 2022/06/23 09:08:40.512878 [INF]   Recovering 3 consumers for stream - "MAIN"
[8736] 2022/06/23 09:08:40.520590 [INF] Listening for client connections on 0.0.0.0:4222
[8736] 2022/06/23 09:08:40.607587 [INF] Server is ready
```

My .NET code using the default connection logic:
```
var options = ConnectionFactory.GetDefaultOptions();
            options.Url = url;
            options.Name = name;
            options.Timeout = timeout;
            options.Verbose = true;
            options.AsyncErrorEventHandler += (sender, args) =>
            {
                logger.LogError("NATS: Error: Server: {connectedUrl}. Message: {error}. Subject: {subject}", args.Conn.ConnectedUrl, args.Error, args.Subscription.Subject);
            };
            options.ServerDiscoveredEventHandler += (sender, args) =>
            {
                logger.LogInformation("NATS: A new server has joined the cluster: {servers}", string.Join(", ", args.Conn.DiscoveredServers));
            };
            options.ClosedEventHandler += (sender, args) =>
            {
                logger.LogInformation("NATS: Connection Closed: {message}. Server: {connectedUrl}", args.Error?.Message, args.Conn.ConnectedUrl);
            };
            options.DisconnectedEventHandler += (sender, args) =>
            {
                logger.LogInformation("NATS: Connection Disconnected: {message}. Server: {connectedUrl}.", args.Error?.Message, args.Conn.ConnectedUrl);
            };
return connectionFactory.CreateConnection(options);
```

Exception thrown on line `return connectionFactory.CreateConnection(options);`:
```
   at NATS.Client.Connection.connect()
   at NATS.Client.ConnectionFactory.CreateConnection(Options opts)
```

I moved away from .NET to two Powershell windows:
- Window A: `nats publish "filter.blah.test" "{}"`
- Window B: `nats consumer next STREAM WORKER`

Observations through `nats consumer info STREAM WORKER`:

```
Configuration:
        Durable Name: WORKER
           Pull Mode: true
      Filter Subject: filter.blah.>
      Deliver Policy: New
          Ack Policy: Explicit
       Replay Policy: Instant
     Max Ack Pending: 20,000
   Max Waiting Pulls: 512

State:

   Last Delivered Message: Consumer sequence: 142 Stream sequence: 869
     Acknowledgment floor: Consumer sequence: 142 Stream sequence: 869
         Outstanding Acks: 0 out of maximum 20,000
     Redelivered Messages: 0
     Unprocessed Messages: 0
            Waiting Pulls: 70 of maximum 512
```

- I observe 70 Waiting Pulls
- Window B: `nats consumer next STREAM WORKER`:

```
Configuration:

        Durable Name: WORKER
           Pull Mode: true
      Filter Subject: filter.blah.>
          Ack Policy: Explicit
       Replay Policy: Instant
     Max Ack Pending: 20,000
   Max Waiting Pulls: 512

State:

   Last Delivered Message: Consumer sequence: 142 Stream sequence: 869
     Acknowledgment floor: Consumer sequence: 142 Stream sequence: 869
         Outstanding Acks: 0 out of maximum 20,000
     Redelivered Messages: 0
     Unprocessed Messages: 0
            Waiting Pulls: 72 of maximum 512
```

- I observe the `Waiting Pulls` goes up from 70 to 72 (up by 2). What are Waiting Pulls? I notice that on each `next` they increment by random factors.
- Update: After 8 hours of waiting I see in my .NET app logs that I lost connection to NATS server (Even though I can access NATS with a Powershell window). Restarting the app made it work.
```
NATS.Client.NATSConnectionClosedException: Connection is closed.
   at NATS.Client.Connection.publish(String subject, String reply, Byte[] headers, Byte[] data, Int32 offset, Int32 count, Boolean flushBuffer)
   at NATS.Client.Connection.requestSync(String subject, Byte[] headers, Byte[] data, Int32 offset, Int32 count, Int32 timeout)
   at NATS.Client.Connection.request(String subject, Byte[] headers, Byte[] data, Int32 offset, Int32 count, Int32 timeout)
   at NATS.Client.Connection.Request(String subject, Byte[] data, Int32 timeout)
   at NATS.Client.JetStream.JetStreamBase.RequestResponseRequired(String subject, Byte[] bytes, Int32 timeout)
   at NATS.Client.JetStream.JetStreamBase.GetConsumerInfoInternal(String streamName, String consumer)
   at NATS.Client.JetStream.JetStream.LookupConsumerInfo(String lookupStream, String lookupConsumer)
   at NATS.Client.JetStream.JetStream.CreateSubscription(String subject, String queueName, EventHandler`1 userHandler, Boolean autoAck, PushSubscribeOptions pushSubscribeOptions, PullSubscribeOptions pullSubscribeOptions)
   at NATS.Client.JetStream.JetStream.PullSubscribe(String subject, PullSubscribeOptions options)
```

**Comment by scottf** [comment]
1. Pull waiting. When a program makes a pull request it gets queued until it is resolved, which accounts for the build up of waiting. My guess is that these were make with no expire time, so only will be completed if the batch size is actually fulfilled.
What is the code that is making the pulls?
2. Try adding in ReconnectedEventHandler
3. your consumer configuration shows zero unprocessed messages. Seems like the consumer has nothing to do.
