### ISSUE TITLE
Not thread safe to start subscriptions concurrently in a connection

### ISSUE THREAD

**Issue by MENNAELMESALMY** [nats-io/nats.net.v1#917]
### Observed behavior

we saw this error getting thrown when trying to start multiple subscriptions concurrently

```
"   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at NATS.Client.Connection.AddSubscription(Subscription s)
   at NATS.Client.Connection.subscribeAsync(String subject, String queue, EventHandler`1 handler, CreateAsyncSubscriptionDelegate createAsyncSubscriptionDelegate)
   at NATS.Client.JetStream.JetStream.CreateSubscription(String userSubscribeSubject, PushSubscribeOptions pushSubscribeOptions, PullSubscribeOptions pullSubscribeOptions, String queueName, EventHandler`1 userHandler, Boolean autoAck, PullMessageManager pmmInstance)
   at NATS.Client.JetStream.JetStream.PushSubscribeAsync(String subject, EventHandler`1 handler, Boolean autoAck, PushSubscribeOptions options)
   at NATS.Client.KeyValue.KeyValueWatchSubscription..ctor(KeyValue kv, IList`1 keyPatterns, IKeyValueWatcher watcher, UInt64 fromRevision, KeyValueWatchOption[] watchOptions)
   at NATS.Client.KeyValue.KeyValue.WatchAll(IKeyValueWatcher watcher, KeyValueWatchOption[] watchOptions)

...

```
I saw that the connection keeps track of all subscriptions [in a dictionary](https://github.com/nats-io/nats.net.v1/blob/f0eb9187ce498dc802f81435c169f092ee3f5144/src/NATS.Client/Connection.cs#L4173-L4176) but it's not [thread safe](https://stackoverflow.com/questions/15095817/adding-to-a-generic-dictionary-causes-indexoutofrangeexception) 

### Expected behavior

Starting multiple subscriptions is thread-safe.

### Server and client version

c# version: 1.1.5

**Comment by MENNAELMESALMY** [comment]
also, this could happen if we are adding a subscription, and another ordered subscription starts getting a heartbeat so also resubscribing.

**Comment by scottf** [comment]
@MENNAELMESALMY Can you please have a look at this PR https://github.com/nats-io/nats.net.v1/pull/921
I changed to concurrent dictionary.

**Comment by MENNAELMESALMY** [comment]
LGTM, Thanks @scottf!
